### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: this.javaClass.getResour…ta/addition_blo ks.json")

### ISSUE THREAD

**Issue by cardanawandra** [UnlegitMC/FilhoConnect#1]
14:56:45 [INFO ] Starting FilhoConnect v0.0.1...
Exception in thread "main" java.lang.NullPointerException: this.javaClass.getResour…ta/addition_blo
ks.json") must not be null
        at today.getfdp.connect.resources.BlockMappingHolder.addPatches(BlockMappingHolder.kt:70)
        at today.getfdp.connect.resources.BlockMappingHolder.init(BlockMappingHolder.kt:63)
        at today.getfdp.connect.resources.ResourceHolder.loadResource(ResourceHolder.kt:41)
        at today.getfdp.connect.FConnect$loadResources$tasks$3.invoke(FConnect.kt:92)
        at today.getfdp.connect.FConnect$loadResources$tasks$3.invoke(FConnect.kt:92)
        at today.getfdp.connect.FConnect.loadResources(FConnect.kt:96)
        at today.getfdp.connect.FConnect.start(FConnect.kt:72)
        at today.getfdp.connect.FConnect.main(FConnect.kt:53)

**Comment by hax0r31337** [comment]
Try update submodule

**Comment by cardanawandra** [comment]
ok

**Comment by cardanawandra** [comment]
Submodule 'src/main/resources/fc-data' (git@github.com:UnlegitMC/fc-data.git) registered for path 'src/main/resources/fc-data'
Cloning into 'D:/optifine/FilhoConnect/src/main/resources/fc-data'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:UnlegitMC/fc-data.git' into submodule path 'D:/optifine/FilhoConnect/src/main/resources/fc-data' failed
Failed to clone 'src/main/resources/fc-data'. Retry scheduled
Cloning into 'D:/optifine/FilhoConnect/src/main/resources/fc-data'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:UnlegitMC/fc-data.git' into submodule path 'D:/optifine/FilhoConnect/src/main/resources/fc-data' failed
Failed to clone 'src/main/resources/fc-data' a second time, aborting
